version: "3.8"

services:
  app:
    container_name: aspnet_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # HTTP Port
      - "5001:5001" # HTTPS Port
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=mydb;Username=postgres;Password=example
    depends_on:
      - db
    volumes:
      - .:/app # Mounting the current directory to the /app directory inside the container for live reload
      - /app/bin # Ensures the bin directory is not overwritten
      - /app/obj # Ensures the obj directory is not overwritten
    command: dotnet watch run # This enables hot reload via dotnet watch
    working_dir: /app # Ensure the app runs in the correct directory inside the container

  db:
    container_name: postgres_db
    image: postgres:15
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
