version: "3.8"

services:
  app:
    container_name: aspnet_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=swimmingappdb;Username=${DB_USERNAME};Password=${DB_PASSWORD}

  db:
    container_name: postgres_db
    image: postgres:15
    environment:
      POSTGRES_DB: swimmingappdb
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
volumes:
  pg_data:
