version: "3.8"

services:
  app:
    container_name: swimming_app_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:5000"
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING_PROD}

  db:
    container_name: swimming_app_db
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_DB: swimmingappdb
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
volumes:
  pg_data:
