// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SwimmingAppBackend.Infrastructure.Context;

#nullable disable

namespace Swimming_App_Backend.Migrations
{
    [DbContext(typeof(SwimmingAppDBContext))]
    partial class SwimmingAppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "breathing_options_enum", new[] { "unselected", "normal", "fast", "deep", "erratic" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "catch_feel_options_enum", new[] { "unselected", "strong", "weak", "slipping", "wide", "narrow" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "energy_level_options_enum", new[] { "unselected", "low", "moderate", "high", "very_high" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "head_position_options_enum", new[] { "unselected", "looking_forward", "looking_down", "head_high", "head_low", "head_neutral" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "kick_technique_options_enum", new[] { "unselected", "small", "big" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "kick_throughout_options_enum", new[] { "unselected", "consistent", "speeding_up", "slowing_down" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "nerves_options_enum", new[] { "unselected", "relaxed", "jittery", "tense", "heavy", "light", "nauseous" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "self_talk_options_enum", new[] { "unselected", "none", "motivational_positive", "motivational_negative", "instructive_positive", "instructive_negative", "outcome_positive", "outcome_negative" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "stroke_length_options_enum", new[] { "unselected", "longer", "shorter" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "turn_options_enum", new[] { "unselected", "good", "too_far", "too_close", "felt_slow", "felt_fast" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SwimmingAppBackend.Infrastructure.Models.Achievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TargetValue")
                        .HasColumnType("integer");

                    b.Property<int>("UserType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Achievements");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Swim a total of 10,000 meters.",
                            Difficulty = 4,
                            Name = "Marathon Swimmer",
                            TargetValue = 10000,
                            UserType = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Description = "Log your first swim session.",
                            Difficulty = 1,
                            Name = "First Swim",
                            TargetValue = 1,
                            UserType = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Description = "Log 20 swims.",
                            Difficulty = 2,
                            Name = "Getting it done",
                            TargetValue = 20,
                            UserType = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Description = "Log 100 swims.",
                            Difficulty = 3,
                            Name = "Busy cooking",
                            TargetValue = 100,
                            UserType = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Description = "Log 200 swims.",
                            Difficulty = 4,
                            Name = "Proper chef",
                            TargetValue = 200,
                            UserType = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Description = "You made your first 1000, congratulations, we gotta do at least 20 bro. Log 1000 swims.",
                            Difficulty = 8,
                            Name = "Gotta do at least 20 bro",
                            TargetValue = 1000,
                            UserType = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Description = "How did you do that? Log 2000 swims",
                            Difficulty = 10,
                            Name = "Ashton Hall",
                            TargetValue = 2000,
                            UserType = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Description = "Account over a year old.",
                            Difficulty = 6,
                            Name = "Unc status",
                            TargetValue = 1,
                            UserType = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Description = "Account over 2 years old.",
                            Difficulty = 8,
                            Name = "Fossil",
                            TargetValue = 1,
                            UserType = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "One of the first 20 users to join.",
                            Difficulty = 10,
                            Name = "Founding member",
                            TargetValue = 1,
                            UserType = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Description = "One of the first 100 users to join.",
                            Difficulty = 8,
                            Name = "Early adopter",
                            TargetValue = 1,
                            UserType = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Description = "One of the first 1000 users to join.",
                            Difficulty = 6,
                            Name = "First 1000",
                            TargetValue = 1,
                            UserType = 0
                        });
                });

            modelBuilder.Entity("SwimmingAppBackend.Infrastructure.Models.AthleteData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserOwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("AthleteDatas");
                });

            modelBuilder.Entity("SwimmingAppBackend.Infrastructure.Models.CoachData", b =>
                {
                    b.Property<Guid>("CoachDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserOwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("CoachDataId");

                    b.ToTable("CoachDatas");
                });

            modelBuilder.Entity("SwimmingAppBackend.Infrastructure.Models.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AddresseeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AddresseeId");

                    b.HasIndex("IsConfirmed");

                    b.HasIndex("RequesterId");

                    b.HasIndex("RequesterId", "AddresseeId")
                        .IsUnique();

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("SwimmingAppBackend.Infrastructure.Models.Split", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Dive")
                        .HasColumnType("boolean");

                    b.Property<int>("IntervalDistance")
                        .HasColumnType("integer");

                    b.Property<int?>("IntervalStrokeCount")
                        .HasColumnType("integer");

                    b.Property<int?>("IntervalStrokeRate")
                        .HasColumnType("integer");

                    b.Property<double>("IntervalTime")
                        .HasColumnType("double precision");

                    b.Property<double?>("PerOffGoalStrokeRate")
                        .HasColumnType("double precision");

                    b.Property<double?>("PerOffGoalTime")
                        .HasColumnType("double precision");

                    b.Property<double?>("PerOffPBIntervalTime")
                        .HasColumnType("double precision");

                    b.Property<double?>("PerOffPBStrokeRate")
                        .HasColumnType("double precision");

                    b.Property<int>("Stroke")
                        .HasColumnType("integer");

                    b.Property<Guid>("SwimId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SwimId");

                    b.ToTable("Splits");
                });

            modelBuilder.Entity("SwimmingAppBackend.Infrastructure.Models.Swim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteDataOwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Event")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ExternalId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ExternalSource")
                        .HasColumnType("integer");

                    b.Property<bool>("GoalSwim")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("boolean");

                    b.Property<int>("PoolType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SwimQuestionnaireId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AthleteDataOwnerId");

                    b.HasIndex("SwimQuestionnaireId");

                    b.ToTable("Swims");
                });

            modelBuilder.Entity("SwimmingAppBackend.Infrastructure.Models.SwimQuestionnaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Breathing")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("CatchFeel")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("EnergyLevel")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("HeadPosition")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("KickTechnique")
                        .HasColumnType("integer");

                    b.Property<int>("KickThroughout")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("Nerves")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("SelfTalk")
                        .HasColumnType("integer");

                    b.Property<int>("StrokeLength")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("Turn")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("Id");

                    b.ToTable("SwimQuestionnaire");
                });

            modelBuilder.Entity("SwimmingAppBackend.Infrastructure.Models.TimeSheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Event")
                        .HasColumnType("integer");

                    b.Property<string>("SplitDataForTimes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TimeSheets");
                });

            modelBuilder.Entity("SwimmingAppBackend.Infrastructure.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AthleteDataId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CoachDataId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<double?>("Height")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AthleteDataId")
                        .IsUnique();

                    b.HasIndex("CoachDataId")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SwimmingAppBackend.Infrastructure.Models.UserAchievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AchievementId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EarnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Progress")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.HasIndex("UserId", "AchievementId")
                        .IsUnique();

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("SwimmingAppBackend.Infrastructure.Models.UserSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("OriginalTransactionId")
                        .HasColumnType("text");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("PurchaseToken")
                        .HasColumnType("text");

                    b.Property<string>("Receipt")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("SwimmingAppBackend.Infrastructure.Models.Friendship", b =>
                {
                    b.HasOne("SwimmingAppBackend.Infrastructure.Models.User", "Addressee")
                        .WithMany("ReceivedFriendRequests")
                        .HasForeignKey("AddresseeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SwimmingAppBackend.Infrastructure.Models.User", "Requester")
                        .WithMany("SentFriendRequests")
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Addressee");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("SwimmingAppBackend.Infrastructure.Models.Split", b =>
                {
                    b.HasOne("SwimmingAppBackend.Infrastructure.Models.Swim", "Swim")
                        .WithMany("Splits")
                        .HasForeignKey("SwimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Swim");
                });

            modelBuilder.Entity("SwimmingAppBackend.Infrastructure.Models.Swim", b =>
                {
                    b.HasOne("SwimmingAppBackend.Infrastructure.Models.AthleteData", "AthleteDataOwner")
                        .WithMany("Swims")
                        .HasForeignKey("AthleteDataOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwimmingAppBackend.Infrastructure.Models.SwimQuestionnaire", "SwimQuestionnaire")
                        .WithMany()
                        .HasForeignKey("SwimQuestionnaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AthleteDataOwner");

                    b.Navigation("SwimQuestionnaire");
                });

            modelBuilder.Entity("SwimmingAppBackend.Infrastructure.Models.User", b =>
                {
                    b.HasOne("SwimmingAppBackend.Infrastructure.Models.AthleteData", "AthleteData")
                        .WithOne("UserOwner")
                        .HasForeignKey("SwimmingAppBackend.Infrastructure.Models.User", "AthleteDataId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SwimmingAppBackend.Infrastructure.Models.CoachData", "CoachData")
                        .WithOne("UserOwner")
                        .HasForeignKey("SwimmingAppBackend.Infrastructure.Models.User", "CoachDataId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AthleteData");

                    b.Navigation("CoachData");
                });

            modelBuilder.Entity("SwimmingAppBackend.Infrastructure.Models.UserAchievement", b =>
                {
                    b.HasOne("SwimmingAppBackend.Infrastructure.Models.Achievement", "Achievement")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwimmingAppBackend.Infrastructure.Models.User", "User")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SwimmingAppBackend.Infrastructure.Models.UserSubscription", b =>
                {
                    b.HasOne("SwimmingAppBackend.Infrastructure.Models.User", "User")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SwimmingAppBackend.Infrastructure.Models.Achievement", b =>
                {
                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("SwimmingAppBackend.Infrastructure.Models.AthleteData", b =>
                {
                    b.Navigation("Swims");

                    b.Navigation("UserOwner")
                        .IsRequired();
                });

            modelBuilder.Entity("SwimmingAppBackend.Infrastructure.Models.CoachData", b =>
                {
                    b.Navigation("UserOwner")
                        .IsRequired();
                });

            modelBuilder.Entity("SwimmingAppBackend.Infrastructure.Models.Swim", b =>
                {
                    b.Navigation("Splits");
                });

            modelBuilder.Entity("SwimmingAppBackend.Infrastructure.Models.User", b =>
                {
                    b.Navigation("ReceivedFriendRequests");

                    b.Navigation("SentFriendRequests");

                    b.Navigation("UserAchievements");

                    b.Navigation("UserSubscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
