// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SwimmingAppBackend.Context;

#nullable disable

namespace SwimmingAppBackend.Migrations
{
    [DbContext(typeof(SwimmingAppDBContext))]
    partial class SwimmingAppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SwimmingAppBackend.Models.CoachProfile", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("CoachProfile");
                });

            modelBuilder.Entity("SwimmingAppBackend.Models.Set", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("quoteOfTheSet")
                        .HasColumnType("text");

                    b.Property<int>("squadId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("squadId");

                    b.ToTable("Set");
                });

            modelBuilder.Entity("SwimmingAppBackend.Models.Split", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("distance")
                        .HasColumnType("integer");

                    b.Property<bool?>("dive")
                        .HasColumnType("boolean");

                    b.Property<int?>("pace")
                        .HasColumnType("integer");

                    b.Property<int?>("perceivedExertion")
                        .HasColumnType("integer");

                    b.Property<string>("stroke")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("strokeRate")
                        .HasColumnType("integer");

                    b.Property<int>("swimId")
                        .HasColumnType("integer");

                    b.Property<int?>("time")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("swimId");

                    b.ToTable("Split");
                });

            modelBuilder.Entity("SwimmingAppBackend.Models.Squad", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("coachId")
                        .HasColumnType("integer");

                    b.Property<string>("squadName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("coachId");

                    b.ToTable("Squad");
                });

            modelBuilder.Entity("SwimmingAppBackend.Models.Swim", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("distance")
                        .HasColumnType("integer");

                    b.Property<bool?>("dive")
                        .HasColumnType("boolean");

                    b.Property<int?>("heartRate")
                        .HasColumnType("integer");

                    b.Property<int?>("pace")
                        .HasColumnType("integer");

                    b.Property<int?>("perceivedExertion")
                        .HasColumnType("integer");

                    b.Property<string>("stroke")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("strokeRate")
                        .HasColumnType("integer");

                    b.Property<int>("swimmerProfileId")
                        .HasColumnType("integer");

                    b.Property<string>("time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("swimmerProfileId");

                    b.ToTable("Swim");
                });

            modelBuilder.Entity("SwimmingAppBackend.Models.SwimmerProfile", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("goalTime")
                        .HasColumnType("text");

                    b.Property<int?>("mainDistance")
                        .HasColumnType("integer");

                    b.Property<string>("mainStroke")
                        .HasColumnType("text");

                    b.Property<int?>("squadId")
                        .HasColumnType("integer");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("squadId");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("SwimmerProfile");
                });

            modelBuilder.Entity("SwimmingAppBackend.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("age")
                        .HasColumnType("integer");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phoneNum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("SwimmingAppBackend.Models.CoachProfile", b =>
                {
                    b.HasOne("SwimmingAppBackend.Models.User", "user")
                        .WithOne("coachProfile")
                        .HasForeignKey("SwimmingAppBackend.Models.CoachProfile", "userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("SwimmingAppBackend.Models.Set", b =>
                {
                    b.HasOne("SwimmingAppBackend.Models.Squad", "squad")
                        .WithMany("sets")
                        .HasForeignKey("squadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("squad");
                });

            modelBuilder.Entity("SwimmingAppBackend.Models.Split", b =>
                {
                    b.HasOne("SwimmingAppBackend.Models.Swim", "swim")
                        .WithMany("splits")
                        .HasForeignKey("swimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("swim");
                });

            modelBuilder.Entity("SwimmingAppBackend.Models.Squad", b =>
                {
                    b.HasOne("SwimmingAppBackend.Models.CoachProfile", "coachProfile")
                        .WithMany("squads")
                        .HasForeignKey("coachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("coachProfile");
                });

            modelBuilder.Entity("SwimmingAppBackend.Models.Swim", b =>
                {
                    b.HasOne("SwimmingAppBackend.Models.SwimmerProfile", "swimmerProfile")
                        .WithMany("swims")
                        .HasForeignKey("swimmerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("swimmerProfile");
                });

            modelBuilder.Entity("SwimmingAppBackend.Models.SwimmerProfile", b =>
                {
                    b.HasOne("SwimmingAppBackend.Models.Squad", "squad")
                        .WithMany("swimmers")
                        .HasForeignKey("squadId");

                    b.HasOne("SwimmingAppBackend.Models.User", "user")
                        .WithOne("swimmerProfile")
                        .HasForeignKey("SwimmingAppBackend.Models.SwimmerProfile", "userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("squad");

                    b.Navigation("user");
                });

            modelBuilder.Entity("SwimmingAppBackend.Models.CoachProfile", b =>
                {
                    b.Navigation("squads");
                });

            modelBuilder.Entity("SwimmingAppBackend.Models.Squad", b =>
                {
                    b.Navigation("sets");

                    b.Navigation("swimmers");
                });

            modelBuilder.Entity("SwimmingAppBackend.Models.Swim", b =>
                {
                    b.Navigation("splits");
                });

            modelBuilder.Entity("SwimmingAppBackend.Models.SwimmerProfile", b =>
                {
                    b.Navigation("swims");
                });

            modelBuilder.Entity("SwimmingAppBackend.Models.User", b =>
                {
                    b.Navigation("coachProfile");

                    b.Navigation("swimmerProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
