name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main  # Deploy when there's a push to main (or any other branch you prefer)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t your-docker-username/your-app-name:latest .

      - name: Push Docker image to Docker Hub
        run: docker push your-docker-username/your-app-name:latest
